name: Generate-Snake-Animation

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            out/github-snake.svg
            out/github-snake-dark.svg?palette=github-dark

      - name: Commit files
        run: |
          git add out/
          git config --local user.email "bot@nn.ci"
          git config --local user.name "Bot"
          git commit --allow-empty -m "update github-contribution-grid-snake.svg" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
